# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import simulator_pb2 as simulator__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in simulator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SimulationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.create_simulation = channel.unary_unary(
                '/simulator.SimulationService/create_simulation',
                request_serializer=simulator__pb2.CreateSimulationRquest.SerializeToString,
                response_deserializer=simulator__pb2.SimulationResponse.FromString,
                _registered_method=True)
        self.get_simulation = channel.unary_unary(
                '/simulator.SimulationService/get_simulation',
                request_serializer=simulator__pb2.GetSimulationRequest.SerializeToString,
                response_deserializer=simulator__pb2.SimulationResponse.FromString,
                _registered_method=True)
        self.set_logist = channel.unary_unary(
                '/simulator.SimulationService/set_logist',
                request_serializer=simulator__pb2.SetLogistRequest.SerializeToString,
                response_deserializer=simulator__pb2.SimulationResponse.FromString,
                _registered_method=True)
        self.add_supplier = channel.unary_unary(
                '/simulator.SimulationService/add_supplier',
                request_serializer=simulator__pb2.AddSupplierRequest.SerializeToString,
                response_deserializer=simulator__pb2.SimulationResponse.FromString,
                _registered_method=True)
        self.delete_supplier = channel.unary_unary(
                '/simulator.SimulationService/delete_supplier',
                request_serializer=simulator__pb2.DeleteSupplierRequest.SerializeToString,
                response_deserializer=simulator__pb2.SimulationResponse.FromString,
                _registered_method=True)
        self.set_warehouse_inventory_worker = channel.unary_unary(
                '/simulator.SimulationService/set_warehouse_inventory_worker',
                request_serializer=simulator__pb2.SetWarehouseInventoryWorkerRequest.SerializeToString,
                response_deserializer=simulator__pb2.SimulationResponse.FromString,
                _registered_method=True)
        self.increase_warehouse_size = channel.unary_unary(
                '/simulator.SimulationService/increase_warehouse_size',
                request_serializer=simulator__pb2.IncreaseWarehouseSizeRequest.SerializeToString,
                response_deserializer=simulator__pb2.SimulationResponse.FromString,
                _registered_method=True)
        self.add_process_rote = channel.unary_unary(
                '/simulator.SimulationService/add_process_rote',
                request_serializer=simulator__pb2.AddProcessRouteRequest.SerializeToString,
                response_deserializer=simulator__pb2.SimulationResponse.FromString,
                _registered_method=True)
        self.delete_process_rote = channel.unary_unary(
                '/simulator.SimulationService/delete_process_rote',
                request_serializer=simulator__pb2.DeleteProcesRouteRequest.SerializeToString,
                response_deserializer=simulator__pb2.SimulationResponse.FromString,
                _registered_method=True)
        self.set_worker_on_workerplace = channel.unary_unary(
                '/simulator.SimulationService/set_worker_on_workerplace',
                request_serializer=simulator__pb2.SetWorkerOnWorkerplaceRequest.SerializeToString,
                response_deserializer=simulator__pb2.SimulationResponse.FromString,
                _registered_method=True)
        self.set_equipment_on_workplace = channel.unary_unary(
                '/simulator.SimulationService/set_equipment_on_workplace',
                request_serializer=simulator__pb2.SetEquipmentOnWorkplaceRequst.SerializeToString,
                response_deserializer=simulator__pb2.SimulationResponse.FromString,
                _registered_method=True)
        self.unset_worker_on_workerplace = channel.unary_unary(
                '/simulator.SimulationService/unset_worker_on_workerplace',
                request_serializer=simulator__pb2.UnSetWorkerOnWorkerplaceRequest.SerializeToString,
                response_deserializer=simulator__pb2.SimulationResponse.FromString,
                _registered_method=True)
        self.unset_equipment_on_workplace = channel.unary_unary(
                '/simulator.SimulationService/unset_equipment_on_workplace',
                request_serializer=simulator__pb2.UnSetEquipmentOnWorkplaceRequst.SerializeToString,
                response_deserializer=simulator__pb2.SimulationResponse.FromString,
                _registered_method=True)
        self.add_tender = channel.unary_unary(
                '/simulator.SimulationService/add_tender',
                request_serializer=simulator__pb2.AddTenderRequest.SerializeToString,
                response_deserializer=simulator__pb2.SimulationResponse.FromString,
                _registered_method=True)
        self.delete_tender = channel.unary_unary(
                '/simulator.SimulationService/delete_tender',
                request_serializer=simulator__pb2.RemoveTenderRequest.SerializeToString,
                response_deserializer=simulator__pb2.SimulationResponse.FromString,
                _registered_method=True)
        self.set_dealing_with_defects = channel.unary_unary(
                '/simulator.SimulationService/set_dealing_with_defects',
                request_serializer=simulator__pb2.SetDealingWithDefectsRequest.SerializeToString,
                response_deserializer=simulator__pb2.SimulationResponse.FromString,
                _registered_method=True)
        self.set_has_certification = channel.unary_unary(
                '/simulator.SimulationService/set_has_certification',
                request_serializer=simulator__pb2.SetHasCertificationRequest.SerializeToString,
                response_deserializer=simulator__pb2.SimulationResponse.FromString,
                _registered_method=True)
        self.add_production_improvement = channel.unary_unary(
                '/simulator.SimulationService/add_production_improvement',
                request_serializer=simulator__pb2.AddProductionImprovementRequest.SerializeToString,
                response_deserializer=simulator__pb2.SimulationResponse.FromString,
                _registered_method=True)
        self.delete_production_improvement = channel.unary_unary(
                '/simulator.SimulationService/delete_production_improvement',
                request_serializer=simulator__pb2.DeleteProductionImprovementRequest.SerializeToString,
                response_deserializer=simulator__pb2.SimulationResponse.FromString,
                _registered_method=True)
        self.set_sales_strategy = channel.unary_unary(
                '/simulator.SimulationService/set_sales_strategy',
                request_serializer=simulator__pb2.SetSalesStrategyRequest.SerializeToString,
                response_deserializer=simulator__pb2.SimulationResponse.FromString,
                _registered_method=True)
        self.run_simulation = channel.unary_unary(
                '/simulator.SimulationService/run_simulation',
                request_serializer=simulator__pb2.RunSimulationRequest.SerializeToString,
                response_deserializer=simulator__pb2.SimulationResponse.FromString,
                _registered_method=True)
        self.ping = channel.unary_unary(
                '/simulator.SimulationService/ping',
                request_serializer=simulator__pb2.PingRequest.SerializeToString,
                response_deserializer=simulator__pb2.SuccessResponse.FromString,
                _registered_method=True)


class SimulationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def create_simulation(self, request, context):
        """возвращает пустую симуляцию (параметры заполняются через геттеры и сеттеры)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_simulation(self, request, context):
        """получаем симуляцию по id 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def set_logist(self, request, context):
        """устанавливаем логиста
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def add_supplier(self, request, context):
        """добавляем поставщика
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete_supplier(self, request, context):
        """удаляем поставщика
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def set_warehouse_inventory_worker(self, request, context):
        """устанавливаем работника на склад
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def increase_warehouse_size(self, request, context):
        """увеличиваем размер склада
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def add_process_rote(self, request, context):
        """Добавляем путь для логиста
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete_process_rote(self, request, context):
        """Удафлем путь для логиста
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def set_worker_on_workerplace(self, request, context):
        """Устанавливаем работника на рабочее место
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def set_equipment_on_workplace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def unset_worker_on_workerplace(self, request, context):
        """убираем работника с рабочего места
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def unset_equipment_on_workplace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def add_tender(self, request, context):
        """добавляем тендер
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete_tender(self, request, context):
        """удаляем тендер
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def set_dealing_with_defects(self, request, context):
        """устанавливаем политику работы с браком
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def set_has_certification(self, request, context):
        """устанавливаем сертификацию ГОСТ Р ИСО
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def add_production_improvement(self, request, context):
        """добавляем улучшение производства
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete_production_improvement(self, request, context):
        """удаляем улучшение производства
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def set_sales_strategy(self, request, context):
        """устанавливаем стратегию продаж
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def run_simulation(self, request, context):
        """запускаем симуляцию
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ping(self, request, context):
        """проверка сервиса
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimulationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'create_simulation': grpc.unary_unary_rpc_method_handler(
                    servicer.create_simulation,
                    request_deserializer=simulator__pb2.CreateSimulationRquest.FromString,
                    response_serializer=simulator__pb2.SimulationResponse.SerializeToString,
            ),
            'get_simulation': grpc.unary_unary_rpc_method_handler(
                    servicer.get_simulation,
                    request_deserializer=simulator__pb2.GetSimulationRequest.FromString,
                    response_serializer=simulator__pb2.SimulationResponse.SerializeToString,
            ),
            'set_logist': grpc.unary_unary_rpc_method_handler(
                    servicer.set_logist,
                    request_deserializer=simulator__pb2.SetLogistRequest.FromString,
                    response_serializer=simulator__pb2.SimulationResponse.SerializeToString,
            ),
            'add_supplier': grpc.unary_unary_rpc_method_handler(
                    servicer.add_supplier,
                    request_deserializer=simulator__pb2.AddSupplierRequest.FromString,
                    response_serializer=simulator__pb2.SimulationResponse.SerializeToString,
            ),
            'delete_supplier': grpc.unary_unary_rpc_method_handler(
                    servicer.delete_supplier,
                    request_deserializer=simulator__pb2.DeleteSupplierRequest.FromString,
                    response_serializer=simulator__pb2.SimulationResponse.SerializeToString,
            ),
            'set_warehouse_inventory_worker': grpc.unary_unary_rpc_method_handler(
                    servicer.set_warehouse_inventory_worker,
                    request_deserializer=simulator__pb2.SetWarehouseInventoryWorkerRequest.FromString,
                    response_serializer=simulator__pb2.SimulationResponse.SerializeToString,
            ),
            'increase_warehouse_size': grpc.unary_unary_rpc_method_handler(
                    servicer.increase_warehouse_size,
                    request_deserializer=simulator__pb2.IncreaseWarehouseSizeRequest.FromString,
                    response_serializer=simulator__pb2.SimulationResponse.SerializeToString,
            ),
            'add_process_rote': grpc.unary_unary_rpc_method_handler(
                    servicer.add_process_rote,
                    request_deserializer=simulator__pb2.AddProcessRouteRequest.FromString,
                    response_serializer=simulator__pb2.SimulationResponse.SerializeToString,
            ),
            'delete_process_rote': grpc.unary_unary_rpc_method_handler(
                    servicer.delete_process_rote,
                    request_deserializer=simulator__pb2.DeleteProcesRouteRequest.FromString,
                    response_serializer=simulator__pb2.SimulationResponse.SerializeToString,
            ),
            'set_worker_on_workerplace': grpc.unary_unary_rpc_method_handler(
                    servicer.set_worker_on_workerplace,
                    request_deserializer=simulator__pb2.SetWorkerOnWorkerplaceRequest.FromString,
                    response_serializer=simulator__pb2.SimulationResponse.SerializeToString,
            ),
            'set_equipment_on_workplace': grpc.unary_unary_rpc_method_handler(
                    servicer.set_equipment_on_workplace,
                    request_deserializer=simulator__pb2.SetEquipmentOnWorkplaceRequst.FromString,
                    response_serializer=simulator__pb2.SimulationResponse.SerializeToString,
            ),
            'unset_worker_on_workerplace': grpc.unary_unary_rpc_method_handler(
                    servicer.unset_worker_on_workerplace,
                    request_deserializer=simulator__pb2.UnSetWorkerOnWorkerplaceRequest.FromString,
                    response_serializer=simulator__pb2.SimulationResponse.SerializeToString,
            ),
            'unset_equipment_on_workplace': grpc.unary_unary_rpc_method_handler(
                    servicer.unset_equipment_on_workplace,
                    request_deserializer=simulator__pb2.UnSetEquipmentOnWorkplaceRequst.FromString,
                    response_serializer=simulator__pb2.SimulationResponse.SerializeToString,
            ),
            'add_tender': grpc.unary_unary_rpc_method_handler(
                    servicer.add_tender,
                    request_deserializer=simulator__pb2.AddTenderRequest.FromString,
                    response_serializer=simulator__pb2.SimulationResponse.SerializeToString,
            ),
            'delete_tender': grpc.unary_unary_rpc_method_handler(
                    servicer.delete_tender,
                    request_deserializer=simulator__pb2.RemoveTenderRequest.FromString,
                    response_serializer=simulator__pb2.SimulationResponse.SerializeToString,
            ),
            'set_dealing_with_defects': grpc.unary_unary_rpc_method_handler(
                    servicer.set_dealing_with_defects,
                    request_deserializer=simulator__pb2.SetDealingWithDefectsRequest.FromString,
                    response_serializer=simulator__pb2.SimulationResponse.SerializeToString,
            ),
            'set_has_certification': grpc.unary_unary_rpc_method_handler(
                    servicer.set_has_certification,
                    request_deserializer=simulator__pb2.SetHasCertificationRequest.FromString,
                    response_serializer=simulator__pb2.SimulationResponse.SerializeToString,
            ),
            'add_production_improvement': grpc.unary_unary_rpc_method_handler(
                    servicer.add_production_improvement,
                    request_deserializer=simulator__pb2.AddProductionImprovementRequest.FromString,
                    response_serializer=simulator__pb2.SimulationResponse.SerializeToString,
            ),
            'delete_production_improvement': grpc.unary_unary_rpc_method_handler(
                    servicer.delete_production_improvement,
                    request_deserializer=simulator__pb2.DeleteProductionImprovementRequest.FromString,
                    response_serializer=simulator__pb2.SimulationResponse.SerializeToString,
            ),
            'set_sales_strategy': grpc.unary_unary_rpc_method_handler(
                    servicer.set_sales_strategy,
                    request_deserializer=simulator__pb2.SetSalesStrategyRequest.FromString,
                    response_serializer=simulator__pb2.SimulationResponse.SerializeToString,
            ),
            'run_simulation': grpc.unary_unary_rpc_method_handler(
                    servicer.run_simulation,
                    request_deserializer=simulator__pb2.RunSimulationRequest.FromString,
                    response_serializer=simulator__pb2.SimulationResponse.SerializeToString,
            ),
            'ping': grpc.unary_unary_rpc_method_handler(
                    servicer.ping,
                    request_deserializer=simulator__pb2.PingRequest.FromString,
                    response_serializer=simulator__pb2.SuccessResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'simulator.SimulationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('simulator.SimulationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SimulationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def create_simulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationService/create_simulation',
            simulator__pb2.CreateSimulationRquest.SerializeToString,
            simulator__pb2.SimulationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_simulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationService/get_simulation',
            simulator__pb2.GetSimulationRequest.SerializeToString,
            simulator__pb2.SimulationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def set_logist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationService/set_logist',
            simulator__pb2.SetLogistRequest.SerializeToString,
            simulator__pb2.SimulationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def add_supplier(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationService/add_supplier',
            simulator__pb2.AddSupplierRequest.SerializeToString,
            simulator__pb2.SimulationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def delete_supplier(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationService/delete_supplier',
            simulator__pb2.DeleteSupplierRequest.SerializeToString,
            simulator__pb2.SimulationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def set_warehouse_inventory_worker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationService/set_warehouse_inventory_worker',
            simulator__pb2.SetWarehouseInventoryWorkerRequest.SerializeToString,
            simulator__pb2.SimulationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def increase_warehouse_size(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationService/increase_warehouse_size',
            simulator__pb2.IncreaseWarehouseSizeRequest.SerializeToString,
            simulator__pb2.SimulationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def add_process_rote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationService/add_process_rote',
            simulator__pb2.AddProcessRouteRequest.SerializeToString,
            simulator__pb2.SimulationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def delete_process_rote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationService/delete_process_rote',
            simulator__pb2.DeleteProcesRouteRequest.SerializeToString,
            simulator__pb2.SimulationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def set_worker_on_workerplace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationService/set_worker_on_workerplace',
            simulator__pb2.SetWorkerOnWorkerplaceRequest.SerializeToString,
            simulator__pb2.SimulationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def set_equipment_on_workplace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationService/set_equipment_on_workplace',
            simulator__pb2.SetEquipmentOnWorkplaceRequst.SerializeToString,
            simulator__pb2.SimulationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def unset_worker_on_workerplace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationService/unset_worker_on_workerplace',
            simulator__pb2.UnSetWorkerOnWorkerplaceRequest.SerializeToString,
            simulator__pb2.SimulationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def unset_equipment_on_workplace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationService/unset_equipment_on_workplace',
            simulator__pb2.UnSetEquipmentOnWorkplaceRequst.SerializeToString,
            simulator__pb2.SimulationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def add_tender(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationService/add_tender',
            simulator__pb2.AddTenderRequest.SerializeToString,
            simulator__pb2.SimulationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def delete_tender(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationService/delete_tender',
            simulator__pb2.RemoveTenderRequest.SerializeToString,
            simulator__pb2.SimulationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def set_dealing_with_defects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationService/set_dealing_with_defects',
            simulator__pb2.SetDealingWithDefectsRequest.SerializeToString,
            simulator__pb2.SimulationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def set_has_certification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationService/set_has_certification',
            simulator__pb2.SetHasCertificationRequest.SerializeToString,
            simulator__pb2.SimulationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def add_production_improvement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationService/add_production_improvement',
            simulator__pb2.AddProductionImprovementRequest.SerializeToString,
            simulator__pb2.SimulationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def delete_production_improvement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationService/delete_production_improvement',
            simulator__pb2.DeleteProductionImprovementRequest.SerializeToString,
            simulator__pb2.SimulationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def set_sales_strategy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationService/set_sales_strategy',
            simulator__pb2.SetSalesStrategyRequest.SerializeToString,
            simulator__pb2.SimulationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def run_simulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationService/run_simulation',
            simulator__pb2.RunSimulationRequest.SerializeToString,
            simulator__pb2.SimulationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationService/ping',
            simulator__pb2.PingRequest.SerializeToString,
            simulator__pb2.SuccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SimulationDatabaseManagerStub(object):
    """Проблема – при получении сложного сообщения (с ссылкой на другое сообщение) у нас о вложенной сущности только id а получить инфу не можем. 
    Лучше возвращать сложные сообщения с вложением сообщений а не со ссылкой
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.create_supplier = channel.unary_unary(
                '/simulator.SimulationDatabaseManager/create_supplier',
                request_serializer=simulator__pb2.CreateSupplierRequest.SerializeToString,
                response_deserializer=simulator__pb2.Supplier.FromString,
                _registered_method=True)
        self.update_supplier = channel.unary_unary(
                '/simulator.SimulationDatabaseManager/update_supplier',
                request_serializer=simulator__pb2.UpdateSupplierRequest.SerializeToString,
                response_deserializer=simulator__pb2.Supplier.FromString,
                _registered_method=True)
        self.delete_supplier = channel.unary_unary(
                '/simulator.SimulationDatabaseManager/delete_supplier',
                request_serializer=simulator__pb2.DeleteSupplierRequest.SerializeToString,
                response_deserializer=simulator__pb2.SuccessResponse.FromString,
                _registered_method=True)
        self.get_all_suppliers = channel.unary_unary(
                '/simulator.SimulationDatabaseManager/get_all_suppliers',
                request_serializer=simulator__pb2.GetAllSuppliersRequest.SerializeToString,
                response_deserializer=simulator__pb2.GetAllSuppliersResponse.FromString,
                _registered_method=True)
        self.get_warehouse = channel.unary_unary(
                '/simulator.SimulationDatabaseManager/get_warehouse',
                request_serializer=simulator__pb2.GetWarehouseRequest.SerializeToString,
                response_deserializer=simulator__pb2.Warehouse.FromString,
                _registered_method=True)
        self.create_worker = channel.unary_unary(
                '/simulator.SimulationDatabaseManager/create_worker',
                request_serializer=simulator__pb2.CreateWorkerRequest.SerializeToString,
                response_deserializer=simulator__pb2.Worker.FromString,
                _registered_method=True)
        self.update_worker = channel.unary_unary(
                '/simulator.SimulationDatabaseManager/update_worker',
                request_serializer=simulator__pb2.UpdateWorkerRequest.SerializeToString,
                response_deserializer=simulator__pb2.Worker.FromString,
                _registered_method=True)
        self.delete_worker = channel.unary_unary(
                '/simulator.SimulationDatabaseManager/delete_worker',
                request_serializer=simulator__pb2.DeleteWorkerRequest.SerializeToString,
                response_deserializer=simulator__pb2.SuccessResponse.FromString,
                _registered_method=True)
        self.get_all_workers = channel.unary_unary(
                '/simulator.SimulationDatabaseManager/get_all_workers',
                request_serializer=simulator__pb2.GetAllWorkersRequest.SerializeToString,
                response_deserializer=simulator__pb2.GetAllWorkersResponse.FromString,
                _registered_method=True)
        self.create_logist = channel.unary_unary(
                '/simulator.SimulationDatabaseManager/create_logist',
                request_serializer=simulator__pb2.CreateLogistRequest.SerializeToString,
                response_deserializer=simulator__pb2.Logist.FromString,
                _registered_method=True)
        self.update_logist = channel.unary_unary(
                '/simulator.SimulationDatabaseManager/update_logist',
                request_serializer=simulator__pb2.UpdateLogistRequest.SerializeToString,
                response_deserializer=simulator__pb2.Logist.FromString,
                _registered_method=True)
        self.delete_logist = channel.unary_unary(
                '/simulator.SimulationDatabaseManager/delete_logist',
                request_serializer=simulator__pb2.DeleteLogistRequest.SerializeToString,
                response_deserializer=simulator__pb2.SuccessResponse.FromString,
                _registered_method=True)
        self.get_all_logists = channel.unary_unary(
                '/simulator.SimulationDatabaseManager/get_all_logists',
                request_serializer=simulator__pb2.GetAllLogistsRequest.SerializeToString,
                response_deserializer=simulator__pb2.GetAllLogistsResponse.FromString,
                _registered_method=True)
        self.create_workplace = channel.unary_unary(
                '/simulator.SimulationDatabaseManager/create_workplace',
                request_serializer=simulator__pb2.CreateWorkplaceRequest.SerializeToString,
                response_deserializer=simulator__pb2.Workplace.FromString,
                _registered_method=True)
        self.update_workplace = channel.unary_unary(
                '/simulator.SimulationDatabaseManager/update_workplace',
                request_serializer=simulator__pb2.UpdateWorkplaceRequest.SerializeToString,
                response_deserializer=simulator__pb2.Workplace.FromString,
                _registered_method=True)
        self.delete_workplace = channel.unary_unary(
                '/simulator.SimulationDatabaseManager/delete_workplace',
                request_serializer=simulator__pb2.DeleteWorkplaceRequest.SerializeToString,
                response_deserializer=simulator__pb2.SuccessResponse.FromString,
                _registered_method=True)
        self.get_all_workplaces = channel.unary_unary(
                '/simulator.SimulationDatabaseManager/get_all_workplaces',
                request_serializer=simulator__pb2.GetAllWorkplacesRequest.SerializeToString,
                response_deserializer=simulator__pb2.GetAllWorkplacesResponse.FromString,
                _registered_method=True)
        self.get_process_graph = channel.unary_unary(
                '/simulator.SimulationDatabaseManager/get_process_graph',
                request_serializer=simulator__pb2.GetProcessGraphRequest.SerializeToString,
                response_deserializer=simulator__pb2.ProcessGraph.FromString,
                _registered_method=True)
        self.create_consumer = channel.unary_unary(
                '/simulator.SimulationDatabaseManager/create_consumer',
                request_serializer=simulator__pb2.CreateConsumerRequest.SerializeToString,
                response_deserializer=simulator__pb2.Consumer.FromString,
                _registered_method=True)
        self.update_consumer = channel.unary_unary(
                '/simulator.SimulationDatabaseManager/update_consumer',
                request_serializer=simulator__pb2.UpdateConsumerRequest.SerializeToString,
                response_deserializer=simulator__pb2.Consumer.FromString,
                _registered_method=True)
        self.delete_consumer = channel.unary_unary(
                '/simulator.SimulationDatabaseManager/delete_consumer',
                request_serializer=simulator__pb2.DeleteConsumerRequest.SerializeToString,
                response_deserializer=simulator__pb2.SuccessResponse.FromString,
                _registered_method=True)
        self.get_all_consumers = channel.unary_unary(
                '/simulator.SimulationDatabaseManager/get_all_consumers',
                request_serializer=simulator__pb2.GetAllConsumersRequest.SerializeToString,
                response_deserializer=simulator__pb2.GetAllConsumersResponse.FromString,
                _registered_method=True)
        self.create_tender = channel.unary_unary(
                '/simulator.SimulationDatabaseManager/create_tender',
                request_serializer=simulator__pb2.CreateTenderRequest.SerializeToString,
                response_deserializer=simulator__pb2.Tender.FromString,
                _registered_method=True)
        self.update_tender = channel.unary_unary(
                '/simulator.SimulationDatabaseManager/update_tender',
                request_serializer=simulator__pb2.UpdateTenderRequest.SerializeToString,
                response_deserializer=simulator__pb2.Tender.FromString,
                _registered_method=True)
        self.delete_tender = channel.unary_unary(
                '/simulator.SimulationDatabaseManager/delete_tender',
                request_serializer=simulator__pb2.DeleteTenderRequest.SerializeToString,
                response_deserializer=simulator__pb2.SuccessResponse.FromString,
                _registered_method=True)
        self.get_all_tenders = channel.unary_unary(
                '/simulator.SimulationDatabaseManager/get_all_tenders',
                request_serializer=simulator__pb2.GetAllTendersRequest.SerializeToString,
                response_deserializer=simulator__pb2.GetAllTendersResponse.FromString,
                _registered_method=True)
        self.create_equipment = channel.unary_unary(
                '/simulator.SimulationDatabaseManager/create_equipment',
                request_serializer=simulator__pb2.CreateEquipmentRequest.SerializeToString,
                response_deserializer=simulator__pb2.Equipment.FromString,
                _registered_method=True)
        self.update_equipment = channel.unary_unary(
                '/simulator.SimulationDatabaseManager/update_equipment',
                request_serializer=simulator__pb2.UpdateEquipmentRequest.SerializeToString,
                response_deserializer=simulator__pb2.Equipment.FromString,
                _registered_method=True)
        self.delete_equipment = channel.unary_unary(
                '/simulator.SimulationDatabaseManager/delete_equipment',
                request_serializer=simulator__pb2.DeleteEquipmentRequest.SerializeToString,
                response_deserializer=simulator__pb2.SuccessResponse.FromString,
                _registered_method=True)
        self.get_all_equipment = channel.unary_unary(
                '/simulator.SimulationDatabaseManager/get_all_equipment',
                request_serializer=simulator__pb2.GetAllEquipmentRequest.SerializeToString,
                response_deserializer=simulator__pb2.GetAllEquipmentResopnse.FromString,
                _registered_method=True)
        self.ping = channel.unary_unary(
                '/simulator.SimulationDatabaseManager/ping',
                request_serializer=simulator__pb2.PingRequest.SerializeToString,
                response_deserializer=simulator__pb2.SuccessResponse.FromString,
                _registered_method=True)


class SimulationDatabaseManagerServicer(object):
    """Проблема – при получении сложного сообщения (с ссылкой на другое сообщение) у нас о вложенной сущности только id а получить инфу не можем. 
    Лучше возвращать сложные сообщения с вложением сообщений а не со ссылкой
    """

    def create_supplier(self, request, context):
        """методы поставщика
        из БД
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update_supplier(self, request, context):
        """из БД 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete_supplier(self, request, context):
        """из БД
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_all_suppliers(self, request, context):
        """из БД
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_warehouse(self, request, context):
        """методы склада
        из redis
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def create_worker(self, request, context):
        """методы рабочих
        из БД 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update_worker(self, request, context):
        """из БД
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete_worker(self, request, context):
        """из БД 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_all_workers(self, request, context):
        """из БД 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def create_logist(self, request, context):
        """методы логиста
        из БД 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update_logist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete_logist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_all_logists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def create_workplace(self, request, context):
        """методы рабочих мест 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update_workplace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete_workplace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_all_workplaces(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_process_graph(self, request, context):
        """методы карты процесса 
        из Redis
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def create_consumer(self, request, context):
        """методы заказчика
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update_consumer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete_consumer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_all_consumers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def create_tender(self, request, context):
        """методы тендеров
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update_tender(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete_tender(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_all_tenders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def create_equipment(self, request, context):
        """TODO: реализовать методы менеджемнта equipment
        надо реализовать
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update_equipment(self, request, context):
        """надо реализовать 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete_equipment(self, request, context):
        """надо реализовать 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_all_equipment(self, request, context):
        """надо реализовать
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ping(self, request, context):
        """методы проверки состояния
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimulationDatabaseManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'create_supplier': grpc.unary_unary_rpc_method_handler(
                    servicer.create_supplier,
                    request_deserializer=simulator__pb2.CreateSupplierRequest.FromString,
                    response_serializer=simulator__pb2.Supplier.SerializeToString,
            ),
            'update_supplier': grpc.unary_unary_rpc_method_handler(
                    servicer.update_supplier,
                    request_deserializer=simulator__pb2.UpdateSupplierRequest.FromString,
                    response_serializer=simulator__pb2.Supplier.SerializeToString,
            ),
            'delete_supplier': grpc.unary_unary_rpc_method_handler(
                    servicer.delete_supplier,
                    request_deserializer=simulator__pb2.DeleteSupplierRequest.FromString,
                    response_serializer=simulator__pb2.SuccessResponse.SerializeToString,
            ),
            'get_all_suppliers': grpc.unary_unary_rpc_method_handler(
                    servicer.get_all_suppliers,
                    request_deserializer=simulator__pb2.GetAllSuppliersRequest.FromString,
                    response_serializer=simulator__pb2.GetAllSuppliersResponse.SerializeToString,
            ),
            'get_warehouse': grpc.unary_unary_rpc_method_handler(
                    servicer.get_warehouse,
                    request_deserializer=simulator__pb2.GetWarehouseRequest.FromString,
                    response_serializer=simulator__pb2.Warehouse.SerializeToString,
            ),
            'create_worker': grpc.unary_unary_rpc_method_handler(
                    servicer.create_worker,
                    request_deserializer=simulator__pb2.CreateWorkerRequest.FromString,
                    response_serializer=simulator__pb2.Worker.SerializeToString,
            ),
            'update_worker': grpc.unary_unary_rpc_method_handler(
                    servicer.update_worker,
                    request_deserializer=simulator__pb2.UpdateWorkerRequest.FromString,
                    response_serializer=simulator__pb2.Worker.SerializeToString,
            ),
            'delete_worker': grpc.unary_unary_rpc_method_handler(
                    servicer.delete_worker,
                    request_deserializer=simulator__pb2.DeleteWorkerRequest.FromString,
                    response_serializer=simulator__pb2.SuccessResponse.SerializeToString,
            ),
            'get_all_workers': grpc.unary_unary_rpc_method_handler(
                    servicer.get_all_workers,
                    request_deserializer=simulator__pb2.GetAllWorkersRequest.FromString,
                    response_serializer=simulator__pb2.GetAllWorkersResponse.SerializeToString,
            ),
            'create_logist': grpc.unary_unary_rpc_method_handler(
                    servicer.create_logist,
                    request_deserializer=simulator__pb2.CreateLogistRequest.FromString,
                    response_serializer=simulator__pb2.Logist.SerializeToString,
            ),
            'update_logist': grpc.unary_unary_rpc_method_handler(
                    servicer.update_logist,
                    request_deserializer=simulator__pb2.UpdateLogistRequest.FromString,
                    response_serializer=simulator__pb2.Logist.SerializeToString,
            ),
            'delete_logist': grpc.unary_unary_rpc_method_handler(
                    servicer.delete_logist,
                    request_deserializer=simulator__pb2.DeleteLogistRequest.FromString,
                    response_serializer=simulator__pb2.SuccessResponse.SerializeToString,
            ),
            'get_all_logists': grpc.unary_unary_rpc_method_handler(
                    servicer.get_all_logists,
                    request_deserializer=simulator__pb2.GetAllLogistsRequest.FromString,
                    response_serializer=simulator__pb2.GetAllLogistsResponse.SerializeToString,
            ),
            'create_workplace': grpc.unary_unary_rpc_method_handler(
                    servicer.create_workplace,
                    request_deserializer=simulator__pb2.CreateWorkplaceRequest.FromString,
                    response_serializer=simulator__pb2.Workplace.SerializeToString,
            ),
            'update_workplace': grpc.unary_unary_rpc_method_handler(
                    servicer.update_workplace,
                    request_deserializer=simulator__pb2.UpdateWorkplaceRequest.FromString,
                    response_serializer=simulator__pb2.Workplace.SerializeToString,
            ),
            'delete_workplace': grpc.unary_unary_rpc_method_handler(
                    servicer.delete_workplace,
                    request_deserializer=simulator__pb2.DeleteWorkplaceRequest.FromString,
                    response_serializer=simulator__pb2.SuccessResponse.SerializeToString,
            ),
            'get_all_workplaces': grpc.unary_unary_rpc_method_handler(
                    servicer.get_all_workplaces,
                    request_deserializer=simulator__pb2.GetAllWorkplacesRequest.FromString,
                    response_serializer=simulator__pb2.GetAllWorkplacesResponse.SerializeToString,
            ),
            'get_process_graph': grpc.unary_unary_rpc_method_handler(
                    servicer.get_process_graph,
                    request_deserializer=simulator__pb2.GetProcessGraphRequest.FromString,
                    response_serializer=simulator__pb2.ProcessGraph.SerializeToString,
            ),
            'create_consumer': grpc.unary_unary_rpc_method_handler(
                    servicer.create_consumer,
                    request_deserializer=simulator__pb2.CreateConsumerRequest.FromString,
                    response_serializer=simulator__pb2.Consumer.SerializeToString,
            ),
            'update_consumer': grpc.unary_unary_rpc_method_handler(
                    servicer.update_consumer,
                    request_deserializer=simulator__pb2.UpdateConsumerRequest.FromString,
                    response_serializer=simulator__pb2.Consumer.SerializeToString,
            ),
            'delete_consumer': grpc.unary_unary_rpc_method_handler(
                    servicer.delete_consumer,
                    request_deserializer=simulator__pb2.DeleteConsumerRequest.FromString,
                    response_serializer=simulator__pb2.SuccessResponse.SerializeToString,
            ),
            'get_all_consumers': grpc.unary_unary_rpc_method_handler(
                    servicer.get_all_consumers,
                    request_deserializer=simulator__pb2.GetAllConsumersRequest.FromString,
                    response_serializer=simulator__pb2.GetAllConsumersResponse.SerializeToString,
            ),
            'create_tender': grpc.unary_unary_rpc_method_handler(
                    servicer.create_tender,
                    request_deserializer=simulator__pb2.CreateTenderRequest.FromString,
                    response_serializer=simulator__pb2.Tender.SerializeToString,
            ),
            'update_tender': grpc.unary_unary_rpc_method_handler(
                    servicer.update_tender,
                    request_deserializer=simulator__pb2.UpdateTenderRequest.FromString,
                    response_serializer=simulator__pb2.Tender.SerializeToString,
            ),
            'delete_tender': grpc.unary_unary_rpc_method_handler(
                    servicer.delete_tender,
                    request_deserializer=simulator__pb2.DeleteTenderRequest.FromString,
                    response_serializer=simulator__pb2.SuccessResponse.SerializeToString,
            ),
            'get_all_tenders': grpc.unary_unary_rpc_method_handler(
                    servicer.get_all_tenders,
                    request_deserializer=simulator__pb2.GetAllTendersRequest.FromString,
                    response_serializer=simulator__pb2.GetAllTendersResponse.SerializeToString,
            ),
            'create_equipment': grpc.unary_unary_rpc_method_handler(
                    servicer.create_equipment,
                    request_deserializer=simulator__pb2.CreateEquipmentRequest.FromString,
                    response_serializer=simulator__pb2.Equipment.SerializeToString,
            ),
            'update_equipment': grpc.unary_unary_rpc_method_handler(
                    servicer.update_equipment,
                    request_deserializer=simulator__pb2.UpdateEquipmentRequest.FromString,
                    response_serializer=simulator__pb2.Equipment.SerializeToString,
            ),
            'delete_equipment': grpc.unary_unary_rpc_method_handler(
                    servicer.delete_equipment,
                    request_deserializer=simulator__pb2.DeleteEquipmentRequest.FromString,
                    response_serializer=simulator__pb2.SuccessResponse.SerializeToString,
            ),
            'get_all_equipment': grpc.unary_unary_rpc_method_handler(
                    servicer.get_all_equipment,
                    request_deserializer=simulator__pb2.GetAllEquipmentRequest.FromString,
                    response_serializer=simulator__pb2.GetAllEquipmentResopnse.SerializeToString,
            ),
            'ping': grpc.unary_unary_rpc_method_handler(
                    servicer.ping,
                    request_deserializer=simulator__pb2.PingRequest.FromString,
                    response_serializer=simulator__pb2.SuccessResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'simulator.SimulationDatabaseManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('simulator.SimulationDatabaseManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SimulationDatabaseManager(object):
    """Проблема – при получении сложного сообщения (с ссылкой на другое сообщение) у нас о вложенной сущности только id а получить инфу не можем. 
    Лучше возвращать сложные сообщения с вложением сообщений а не со ссылкой
    """

    @staticmethod
    def create_supplier(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationDatabaseManager/create_supplier',
            simulator__pb2.CreateSupplierRequest.SerializeToString,
            simulator__pb2.Supplier.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def update_supplier(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationDatabaseManager/update_supplier',
            simulator__pb2.UpdateSupplierRequest.SerializeToString,
            simulator__pb2.Supplier.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def delete_supplier(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationDatabaseManager/delete_supplier',
            simulator__pb2.DeleteSupplierRequest.SerializeToString,
            simulator__pb2.SuccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_all_suppliers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationDatabaseManager/get_all_suppliers',
            simulator__pb2.GetAllSuppliersRequest.SerializeToString,
            simulator__pb2.GetAllSuppliersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_warehouse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationDatabaseManager/get_warehouse',
            simulator__pb2.GetWarehouseRequest.SerializeToString,
            simulator__pb2.Warehouse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def create_worker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationDatabaseManager/create_worker',
            simulator__pb2.CreateWorkerRequest.SerializeToString,
            simulator__pb2.Worker.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def update_worker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationDatabaseManager/update_worker',
            simulator__pb2.UpdateWorkerRequest.SerializeToString,
            simulator__pb2.Worker.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def delete_worker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationDatabaseManager/delete_worker',
            simulator__pb2.DeleteWorkerRequest.SerializeToString,
            simulator__pb2.SuccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_all_workers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationDatabaseManager/get_all_workers',
            simulator__pb2.GetAllWorkersRequest.SerializeToString,
            simulator__pb2.GetAllWorkersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def create_logist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationDatabaseManager/create_logist',
            simulator__pb2.CreateLogistRequest.SerializeToString,
            simulator__pb2.Logist.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def update_logist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationDatabaseManager/update_logist',
            simulator__pb2.UpdateLogistRequest.SerializeToString,
            simulator__pb2.Logist.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def delete_logist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationDatabaseManager/delete_logist',
            simulator__pb2.DeleteLogistRequest.SerializeToString,
            simulator__pb2.SuccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_all_logists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationDatabaseManager/get_all_logists',
            simulator__pb2.GetAllLogistsRequest.SerializeToString,
            simulator__pb2.GetAllLogistsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def create_workplace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationDatabaseManager/create_workplace',
            simulator__pb2.CreateWorkplaceRequest.SerializeToString,
            simulator__pb2.Workplace.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def update_workplace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationDatabaseManager/update_workplace',
            simulator__pb2.UpdateWorkplaceRequest.SerializeToString,
            simulator__pb2.Workplace.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def delete_workplace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationDatabaseManager/delete_workplace',
            simulator__pb2.DeleteWorkplaceRequest.SerializeToString,
            simulator__pb2.SuccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_all_workplaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationDatabaseManager/get_all_workplaces',
            simulator__pb2.GetAllWorkplacesRequest.SerializeToString,
            simulator__pb2.GetAllWorkplacesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_process_graph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationDatabaseManager/get_process_graph',
            simulator__pb2.GetProcessGraphRequest.SerializeToString,
            simulator__pb2.ProcessGraph.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def create_consumer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationDatabaseManager/create_consumer',
            simulator__pb2.CreateConsumerRequest.SerializeToString,
            simulator__pb2.Consumer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def update_consumer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationDatabaseManager/update_consumer',
            simulator__pb2.UpdateConsumerRequest.SerializeToString,
            simulator__pb2.Consumer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def delete_consumer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationDatabaseManager/delete_consumer',
            simulator__pb2.DeleteConsumerRequest.SerializeToString,
            simulator__pb2.SuccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_all_consumers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationDatabaseManager/get_all_consumers',
            simulator__pb2.GetAllConsumersRequest.SerializeToString,
            simulator__pb2.GetAllConsumersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def create_tender(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationDatabaseManager/create_tender',
            simulator__pb2.CreateTenderRequest.SerializeToString,
            simulator__pb2.Tender.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def update_tender(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationDatabaseManager/update_tender',
            simulator__pb2.UpdateTenderRequest.SerializeToString,
            simulator__pb2.Tender.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def delete_tender(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationDatabaseManager/delete_tender',
            simulator__pb2.DeleteTenderRequest.SerializeToString,
            simulator__pb2.SuccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_all_tenders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationDatabaseManager/get_all_tenders',
            simulator__pb2.GetAllTendersRequest.SerializeToString,
            simulator__pb2.GetAllTendersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def create_equipment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationDatabaseManager/create_equipment',
            simulator__pb2.CreateEquipmentRequest.SerializeToString,
            simulator__pb2.Equipment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def update_equipment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationDatabaseManager/update_equipment',
            simulator__pb2.UpdateEquipmentRequest.SerializeToString,
            simulator__pb2.Equipment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def delete_equipment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationDatabaseManager/delete_equipment',
            simulator__pb2.DeleteEquipmentRequest.SerializeToString,
            simulator__pb2.SuccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_all_equipment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationDatabaseManager/get_all_equipment',
            simulator__pb2.GetAllEquipmentRequest.SerializeToString,
            simulator__pb2.GetAllEquipmentResopnse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulationDatabaseManager/ping',
            simulator__pb2.PingRequest.SerializeToString,
            simulator__pb2.SuccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
